consul:
  image: linyows/consul:0.7
  ports:
    - 8400
    - 8500
    - '53/udp'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  volumes:
    - ./consul/server/config:/config
  command: [consul, agent, -server, -bootstrap, -ui-dir, /ui, -data-dir, /tmp, -config-dir, /config]
vault:
  image: linyows/vault:0.6
  ports:
    - 8200
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - mysql
  volumes:
    - ./vault/config:/config
  command: [supervisord, --nodaemon, --configuration, /config/supervisord.conf]
sshd:
  image: linyows/sshd-vault:0.1
  ports:
    - 22
  links:
    - vault
mysql:
  image: linyows/alpine-mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app
    MYSQL_USER: vault
    MYSQL_PASSWORD: secret
  ports:
    - 3306
  command: ['/entry.sh']
rails:
  image: linyows/vault-rails:latest
  volumes:
    - ./rails/app:/app
  ports:
    - 3000
  links:
    - vault
    - mysql
  command: [supervisord, --nodaemon, --configuration, /supervisord.conf]
#laravel:
#  image: linyows/laravel:5.3
#  volumes:
#    - ./laravel:/app
#  links:
#    - vault:vault
#    - mysql:mysql
