consul:
  hostname: consul
  build: ./consul/server
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  ports:
    - '10053:53/tcp'
    - '10053:53/udp'
    - '8500:8500'
vault:
  hostname: vault
  build: ./vault
  ports:
    - '8200:8200'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - mysql
sshd_ubuntu:
  hostname: ubuntu
  build: ./sshd/ubuntu
  ports:
    - '10022:22'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - vault
sshd_centos:
  hostname: centos
  build: ./sshd/centos
  ports:
    - '10222:22'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - vault
mysql:
  hostname: mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app
    MYSQL_USER: vault
    MYSQL_PASSWORD: secret
  ports:
    - '13306:3306'
rails:
  hostname: rails
  build: ./rails
  volumes:
    - ./rails/app:/app
  ports:
    - '3000:3000'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - vault
    - mysql
#laravel:
#  image: linyows/laravel:5.3
#  volumes:
#    - ./laravel:/app
#  links:
#    - vault:vault
#    - mysql:mysql
#  command: [supervisord, --nodaemon, --configuration=/etc/supervisord.conf]
