vault:
  build: vault/
  ports:
    - 8200:8200
  links:
    - consul:consul
  volumes:
    - ./config:/config
  command: server -config=/config/consul.hcl
consul:
  build: consul-agent/
  ports:
    - 8400:8400
    - 8500:8500
    - 8600:53/udp
  command: consul -server -bootstrap -ui-dir /ui
centos:
  build: centos/
