consul:
  hostname: consul
  container_name: consul
  image: linyows/consul:0.7
  ports:
    - '8400:8400'
    - '8500:8500'
    - '8600:8600/udp'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  volumes:
    - ./consul/server/config:/config
  command: [consul, agent, -server, -bootstrap, -ui-dir, /ui, -data-dir, /tmp, -config-dir, /config]
vault:
  hostname: vault
  container_name: vault
  image: linyows/vault:0.6
  ports:
    - '8200:8200'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - 'consul:consul'
    - 'mysql:mysql'
  volumes:
    - ./vault/config:/config
  command: [supervisord, --nodaemon, --configuration, /config/supervisord.conf]
sshd:
  hostname: sshd
  container_name: sshd
  image: linyows/sshd-vault:0.1
  ports:
    - '2222:22'
  links:
    - 'vault:vault'
mysql:
  hostname: mysql
  container_name: mysql
  image: library/mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: secret
  ports:
    - '13306:3306'
#rails:
#  image: linyows/rails:5.0
#  volumes:
#    - ./rails:/app
#  links:
#    - vault:vault
#    - mysql:mysql
#laravel:
#  image: linyows/laravel:5.3
#  volumes:
#    - ./laravel:/app
#  links:
#    - vault:vault
#    - mysql:mysql
