consul:
  container_name: consul
  image: linyows/consul:0.7
  ports:
    - 8400:8400
    - 8500:8500
    - 8600:8600/udp
  volumes:
    - ./consul/server/config:/config
  command: [agent, -server, -bootstrap, -ui-dir, /ui, -data-dir, /tmp]
vault:
  container_name: vault
  image: linyows/vault:0.6
  ports:
    - 8200:8200
  links:
    - consul:consul
  volumes:
    - ./vault/config:/config
  command: [server, -config=/config/consul.hcl]
