consul:
  hostname: consul
  build: ./consul/server
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  ports:
    - '10053:53/tcp'
    - '10053:53/udp'
    - '8500:8500'
vault-1:
  hostname: vault-1
  build: ./vault
  ports:
    - '8200:8200'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - mysql
vault-2:
  hostname: vault-2
  build: ./vault
  ports:
    - '8201:8200'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - mysql
sshd-1:
  hostname: ubuntu
  build: ./sshd/ubuntu
  ports:
    - '10022:22'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - vault-1
    - vault-2
sshd-2:
  hostname: centos
  build: ./sshd/centos
  ports:
    - '10222:22'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - vault-1
    - vault-2
mysql:
  hostname: mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app
    MYSQL_USER: vault
    MYSQL_PASSWORD: secret
  ports:
    - '13306:3306'
rails:
  hostname: rails
  build: ./rails
  volumes:
    - ./rails/app:/app
  ports:
    - '3000:3000'
  dns:
    - '127.0.0.1'
    - '8.8.8.8'
  links:
    - consul
    - mysql
    - vault-1
    - vault-2
#proxy:
#  image: jwilder/nginx-proxy
#  volumes:
#    - /var/run/docker.sock:/tmp/docker.sock:ro
#    - ./proxy/ssl:/etc/nginx/certs:ro
#    - ./proxy/vhost.d:/etc/nginx/conf.d
#  ports:
#    - 80:80
#    - 443:443
#  links:
#    - consul
#  dns:
#    - '127.0.0.1'
#    - '8.8.8.8'
#    - consul
