# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c87af3bf6a476000c39a339bae0b34866788485abbd553b3b22d95a653e74e78f834aed96102cb542e87158bc945ca6c685f55e58be2d31ddcd3303e3068f660

test:
  secret_key_base: a5944eb85b3001895d7c3e84b73dc50a54dae9fbb354e18233516e2de3032035e348cc8d83830f2fb985849ecd4f7957bed7e1b76db842f8afb3d881aae80ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
